// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lekjfqppeavpgamewzxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxla2pmcXBwZWF2cGdhbWV3enhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzAzNjIsImV4cCI6MjA3Mzk0NjM2Mn0.7sfPL7xFkrtN7uyku68HJwUrJJsjsIFGLRqYOsOF-qs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});